import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { chromium } from 'playwright-core'
const base = process.env.KIRZNER_TEST_URL || 'http://127.0.0.1:4317'
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', args: ['--no-sandbox'], headless: true })
const page = await browser.newPage()
page.setDefaultTimeout(10000)
const errors = []
page.on('pageerror', error => errors.push(error.message))
const input = (name, value, scope = page) => scope.getByLabel(name, { exact: true }).fill(value)
async function submit(name, scope = page, status = 200) {
  const response = page.waitForResponse(r => r.url().endsWith('/api/workspace') && r.request().method() === 'POST')
  await scope.getByRole('button', { name, exact: true }).click()
  const r = await response
  assert.equal(r.status(), status, await r.text())
}
function panel(name) { return page.locator('section.panel').filter({ has: page.getByRole('heading', { name, exact: true }) }) }
try {
  await page.goto(base)
  for (const [name, value] of Object.entries({ Product: 'Synthetic browser test product', 'Target customer': 'Synthetic solo-founder audience', 'Verified capabilities': 'Synthetic fixture only', 'Current business objective': 'Test the full UI loop', 'Available time': '1 hour', 'Available budget': '0', 'Available channels': 'Synthetic owned channel', Constraints: 'No actual outreach or publication' })) await input(name, value)
  await submit('Save business brief')
  await page.locator('nav a').filter({ hasText: 'Opportunities' }).click()
  await input('Research objective', 'Find a synthetic fixture opportunity')
  await input('Selected context and previous findings', 'Synthetic browser fixture')
  await submit('Create research handoff')
  await page.locator('nav a').filter({ hasText: 'Handoffs' }).click()
  const research = panel('Opportunity research · attempt-1')
  const briefResponse = await page.request.get(`${base}/api/handoffs/attempt-1`)
  assert.match(await briefResponse.text(), /Zero to three evidenced opportunities/)
  await input('Stable return ID', 'browser-research', research)
  await input('Return summary', 'Synthetic fixture only; no claim of actual demand', research)
  await research.getByRole('button', { name: 'Add opportunity', exact: true }).click()
  for (const [name, value] of Object.entries({ 'Opportunity title': 'Synthetic UI opportunity', 'Customer relevance': 'Synthetic handoff problem', 'Why now': 'Synthetic demo readiness', Counterevidence: 'No actual demand evidence', Unknowns: 'Demand remains unknown', 'Cheap validation action': 'Prepare a small draft' })) await input(name, value, research)
  await research.getByRole('button', { name: 'Add source', exact: true }).click()
  await input('Source title', 'Real product repository; synthetic test interpretation', research)
  await input('Source URL', 'https://github.com/onsager-ai/kirzner', research)
  await input('What the source supports', 'Product direction only, no acquisition metrics', research)
  await submit('Import return', research)
  await page.locator('nav a').filter({ hasText: 'Opportunities' }).click()
  const opportunity = panel('Synthetic UI opportunity')
  await opportunity.getByLabel('What should happen next?', { exact: true }).selectOption('choose')
  await input('Decision reason', 'Synthetic cheap experiment', opportunity)
  await submit('Record opportunity decision', opportunity)
  await page.locator('nav a').filter({ hasText: 'Experiments' }).click()
  await page.getByLabel('Chosen opportunity', { exact: true }).selectOption('opportunity-1')
  const proposalFields = { 'Target audience': 'Synthetic founder audience', 'Proposed action': 'Synthetic draft test', 'Expected deliverables': 'One synthetic draft', 'Observation window': 'Synthetic seven days', 'Success criteria': 'Synthetic criterion only', 'Failure criteria': 'Synthetic failure criterion', 'Inconclusive criteria': 'Synthetic incomplete window', 'Resource limits': 'Zero spend; no real outreach', 'Preparation authorization scope': 'Prepare only' }
  for (const [name, value] of Object.entries(proposalFields)) await input(name, value)
  await submit('Create experiment')
  const experiment = panel('experiment-1: Synthetic draft test')
  await input('Proposal decision reason', 'Approve synthetic preparation only', experiment)
  await submit('Record proposal decision', experiment)
  await submit('Create preparation handoff', experiment)
  await page.locator('nav a').filter({ hasText: 'Handoffs' }).click()
  const preparation = panel('Experiment preparation · attempt-2')
  await input('Stable return ID', 'browser-preparation', preparation)
  await input('Return summary', 'Synthetic draft returned, no external effects', preparation)
  const uploaded = page.waitForResponse(r => r.url().includes('/api/files?') && r.status() === 200)
  await preparation.getByLabel('Upload a deliverable file', { exact: true }).setInputFiles({ name: 'synthetic-draft.md', mimeType: 'text/markdown', buffer: Buffer.from('# Synthetic browser draft\nNo outreach or business metrics.\n') })
  await uploaded
  await preparation.getByLabel('Deliverable title', { exact: true }).waitFor()
  await submit('Import return', preparation)
  await input('Review note', 'Accepted synthetic draft; no publication or business success', preparation)
  await submit('Record deliverable review', preparation)
  let w = await page.evaluate(() => fetch('/api/workspace').then(r => r.json()))
  assert.equal(w.experiments[0].actions.length, 0)
  assert.equal(w.experiments[0].observations.length, 0)
  await page.locator('nav a').filter({ hasText: 'Results & learning' }).click()
  const result = panel('experiment-1: Synthetic draft test')
  await input('Actual action reference', 'SYNTHETIC browser action log; no real outreach', result)
  await input('What actually happened', 'Synthetic acceptance fixture only', result)
  await submit('Record actual action', result)
  await input('Actual observations and evidence', 'SYNTHETIC: observation window incomplete; no real metrics', result)
  await input('Comparison with original criteria', 'Synthetic comparison against original v1', result)
  await input('Proposed learning', 'Synthetic explicit-adoption test', result)
  await submit('Record business observation', result)
  await result.getByLabel('Next step', { exact: true }).selectOption('adjust')
  await input('Next decision reason', 'Synthetic evidence collection adjustment', result)
  await submit('Record next decision', result)
  await submit('Adopt learning', result)
  await page.reload()
  await page.getByRole('heading', { name: 'Observation observation-1', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Learning adopted', exact: true }).isDisabled(), true)
  // Version authorization and late-return identity remain visible across routes.
  await page.locator('nav a').filter({ hasText: 'Experiments' }).click()
  await experiment.getByRole('button', { name: 'Revise proposal', exact: true }).click()
  await input('Proposed action', 'Synthetic revised draft test', experiment)
  await submit('Save new version', experiment)
  await page.getByText('Needs your decision', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Create preparation handoff', exact: true }).count(), 0)
  await page.locator('nav a').filter({ hasText: 'Handoffs' }).click()
  w = await page.evaluate(() => fetch('/api/workspace').then(r => r.json()))
  const receipt = w.attempts[1].returns[0].input
  const picker = page.getByLabel('Import return file', { exact: true })
  let returned = page.waitForResponse(r => r.url().endsWith('/api/workspace') && r.request().method() === 'POST')
  await picker.setInputFiles({ name: 'duplicate.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(receipt)) })
  assert.equal((await returned).status(), 200)
  returned = page.waitForResponse(r => r.url().endsWith('/api/workspace') && r.request().method() === 'POST')
  await picker.setInputFiles({ name: 'conflict.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...receipt, summary: 'Conflicting synthetic return content' })) })
  assert.equal((await returned).status(), 409)
  await page.getByRole('heading', { name: 'Conflicting returns need inspection', exact: true }).waitFor()
  w = await page.evaluate(() => fetch('/api/workspace').then(r => r.json()))
  assert.equal(w.attempts[1].returns.length, 1)
  assert.equal(w.attempts[1].proposal_version, 1)
  assert.equal(w.experiments[0].observations[0].version, 1)
  assert.equal(w.adopted_learning.length, 1)
  await mkdir('test-results', { recursive: true })
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await page.getByRole('heading', { name: 'Your agent. A clear handoff.', exact: true }).waitFor()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'Mobile layout must not overflow')
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  assert.deepEqual(errors, [])
  console.log('PASS: full synthetic UI journey, file persistence, routing/reload, version approval, duplicate/conflicting imports, explicit learning, mobile layout; no real outreach or metrics.')
} finally { await browser.close() }
